tmkhogares/Models/Security/Accounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Core.Models.Security
{
	public class Accounts
	{
		public Guid? Id { get; set; }
		public string UserName { get; set; }
		public string Name { get; set; }
		public string Password { get; set; }
		public string[] Roles { get; set; }
	}
}

tmkhogares/Controllers/AccountsController.cs
using Core.Models.Security;
using System.Web.Mvc;


namespace ClaroGrandesSuperficies.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Index()
        {
            //SessionPersister.Id = new Guid("F4DA2ADE-CA21-4428-B8A7-FD8A366E07C5");
            //SessionPersister.UserName = "auto generado pruebas";

            if (SessionPersister.Id != null)
                return RedirectToAction("HomeAdmin","Home",null);

            return View();
        }

        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }
            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;
            SessionPersister.Name = ResultUser.Name;
            
           

            return RedirectToAction("index");

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }


        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

tmkhogares/Views/Accounts/AccessDenied.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="container py-5">
    <div class="row">
        <div class="col-md-2 text-center">
            <p><i class="fa fa-exclamation fa-5x"></i><br />Status Code: 403</p>
        </div>
        <div class="col-md-10">
            <h3>OPPSSS!!!! Lo siento...</h3>
            <p>Lo siento,No tienes acceso a esta pagina  por razones de seguridad y de datos sensibles.<br />por favor regresa a la pagina anterior para que sigas Revisando.</p>
            <a class="btn btn-danger" href="javascript:history.back()">Regresar</a>
        </div>
    </div>
</div>

<div id="footer" class="text-center">
    &copy;Uno27 2020, Todos los derechos reservados.
</div>

tmkhogares/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_LayoutLogin.cshtml";

}
@model  Core.Models.Security.AccountsViewModel





<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="active item">Grabaciones</a>
        <div class="right menu">
            <div class="item">
                <a class="ui button">Ingresar</a>
            </div>
        </div>
    </div>
</div>

<!-- menu lateral  -->
<div class="ui inverted vertical masthead center aligned segment">
    <div class="ui container">
        <div class="ui large secondary inverted pointing menu">
            <a class="toc item">
                <i class="sidebar icon"></i>
            </a>
            <a class="active item">Grabaciones</a>
            <div class="right item">
                <a href="#login" class="ui inverted button">Ingresar</a>
            </div>
        </div>
    </div>
    <div class="ui text container">
        <h1 class="ui inverted header">
            Calificacion de Grabaciones
        </h1>
        <h2>Administra Calificaciones de los Asesores.</h2>
        <a href="#login" class="ui huge primary button">Ingresar <i class="right arrow icon"></i></a>
    </div>

</div>

<div class="ui vertical stripe segment" id="login">
    <div class="ui middle aligned stackable grid container">
        <div class="row">
            <div class="eight wide column">
                <h3 class="ui header">Ingresa al sistema de Calificacion de Grabaciones</h3>
                <p>Si tienes problema para ingresar por favor contacta al administrador</p>


                @using (Html.BeginForm("Login", "Accounts", FormMethod.Post, new { @class = "ui large form", autofocus = "" }))
                {


                    <div class="ui stacked segment">
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="user icon"></i>
                                @Html.EditorFor(model => model.Accounts.UserName, new { htmlAttributes = new { @class = "", autofocus = "" } })
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="lock icon"></i>
                                @Html.PasswordFor(model => model.Accounts.Password)
                            </div>
                        </div>
                        <input type="submit" name="send" value="Ingresar" class="ui fluid large purple submit button" />
                    </div>

                    if (ViewBag.Error != null)
                    {

                        <div class="ui error visible  message">@ViewBag.Error</div>
                    }




                }




            </div>
            <div class="six wide right floated column">
                <img src="~/Content/images/uno27_enel.png" class="ui large  rounded image">
            </div>
        </div>

    </div>
</div>




<div class="ui inverted vertical footer segment">
    <div class="ui container">
        <div class="ui stackable inverted divided equal height stackable grid">
            <div class="three wide column">
                <h4 class="ui inverted header">About</h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Sitemap</a>
                    <a href="#" class="item">Contact Us</a>
                    <a href="#" class="item">Religious Ceremonies</a>
                    <a href="#" class="item">Gazebo Plans</a>
                </div>
            </div>
            <div class="three wide column">
                <h4 class="ui inverted header">Services</h4>
                <div class="ui inverted link list">
                    <a href="#" class="item">Banana Pre-Order</a>
                    <a href="#" class="item">DNA FAQ</a>
                    <a href="#" class="item">How To Access</a>
                    <a href="#" class="item">Favorite X-Men</a>
                </div>
            </div>
            <div class="seven wide column">
                <h4 class="ui inverted header">Footer Header</h4>
                <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
            </div>
        </div>
    </div>
</div>





@section Scripts{
    <script>
        // create sidebar and attach to menu open
        $('.ui.sidebar')
        .sidebar('attach events', '.toc.item');

    </script>
}